### PR TITLE
Maven custom installation & proxy authentication support

### PR DESCRIPTION
**Pull request by axel3rd**
Hi,

Features proposal :
- Maven custom installation support
- Proxy authentication support

**Maven custom installation**
- Maven binary used support (for ``mvnDebug.cmd`` or BAT with special context initialization)
- _(Space support in Maven path (windows) --> done by @henryju in commit_ ac5e199612fd76953c56e7d35657983c2e56be4b)

**Proxy authentication support**
- Same user/password for ``http`` & ``https``

Fix unit test for pass in this context.

Best regards

### CODE REVIEW

**Comment by axel3rd** [comment]
I promote this feature, could be useful for executing plugins IT tests (when you are in this case) before send a pull request.

**Comment by simonbrandhof** [comment]
Hi Alix, thanks for the contribution and sorry for the delay. Could you please split the commit so that the 2 improvements on maven and proxy are separated ?

**Comment by axel3rd** [comment]
@simonbrandhof : OK (I need to merge with master furthermore)

**Comment by axel3rd** [comment]
@simonbrandhof : Actions done.

**Comment by simonbrandhof** [comment]
Thanks Alix !

**Comment by axel3rd** [comment]
Thanks Simon. Proud to be the PR n°1 ^^, but more seriously happy to facilitate this component usage with v3.13 for people behind corporate proxy !

**Comment by sns-seb** [comment]
FYI @axel3rd @simonbrandhof, I just reverted the commit "Proxy authentication support" for 2 reasons:

1. it lacked UT coverage
2. adding UT coverage, I didn't manage to make the code work. Seting the proxy authenticator is not enough, the proxy itself must be set

**Comment by henryju** [comment]
@sns-seb not very easy to unit test proxy stuff in Java... we have same problem in GitHub plugin, and I think I'll just accept it "as is".

**Comment by sns-seb** [comment]
@henryju as far as I know, it doesn't work. Also, I did manage to cover this code so, it's two reasons to not accept this change blindly.

**Comment by axel3rd** [comment]
@sns-seb : I will retest the master without [a2b2cdd](https://github.com/SonarSource/orchestrator/commit/a2b2cdd2ac126db2783fb6dbfe27a608ed0bb558) ASAP, on personal (without proxy) and professional (with proxy) computers. Perhaps I did something wrong on the 2 commits split.

@henryju : Are you remind a snippet link I added in a comment about mocking proxy server, during one proxy exchange with you on SonarQube ecosystem ? No way to catch it at this time. Perhaps it could be used for UT on that (more IT ... but perhaps could be recevable)

Sorry for the disagreement and losing time on this PR :(

**Comment by axel3rd** [comment]
> as far as I know, it doesn't work.

@sns-seb : With #18 and removing [a2b2cdd](https://github.com/SonarSource/orchestrator/commit/a2b2cdd2ac126db2783fb6dbfe27a608ed0bb558) (branch on my repo: [ProxySupportVerify](https://github.com/axel3rd/orchestrator/tree/ProxySupportVerify)), I retest all UTs with and without proxy : build is OK (on Windows 10).

Can you detail what it doesn't work in your case ? Thanks in advance.

**Comment by henryju** [comment]
@axel3rd I added recently an IT with proxy in SQ Scanner API: 
https://github.com/SonarSource/sonar-scanner-api/blob/master/its/it-tests/src/test/java/com/sonar/scanner/api/it/ProxyTest.java
Is it what you are referring to?
@sns-seb Note that these ITs are using Orchestrator 3.13-build640. Would be interesting to check that Orchestrator 3.13 final release will still allow these ITs to pass.

**Comment by sns-seb** [comment]
> @sns-seb : With #18 and removing a2b2cdd (branch on my repo: ProxySupportVerify), I retest all UTs with and without proxy : build is OK (on Windows 10).

1/ there is no UT code covering the code added in https://github.com/SonarSource/orchestrator/pull/1/commits/52ef4b98c53ad7fdd40d3405a1b1c67b01242a22 and that's why I looked at this commit in the first place. This makes the Quality Gate of orchestrator fail (lack of coverage on new code). Note that for that reason, no untestable code (ITs do not count) shall be merged.
2/ UTs are supposed to be isolated, so, running on one network or another must not change the results. What do you mean by running "with or without proxy" then?

On my side, I added the following UT to class `URLLocatorTest`. I don't like this UT has its changing the system properties, and this is a reason to change the code and make it actually safely testable. It also could be broken proxy-wise as I don't deal with this area so often.

Still, this test failed with `java.net.ProtocolException: Received HTTP_PROXY_AUTH (407) code while not using proxy` which I assume means that the proxy object is not set on the `OkHttpClient` (and it seems to me that makes sense). First Google result on proxy auth with OkHttp advised to set both properties.

I didn't look much further and reverted as the failing quality gate was blocking orchestrator's release which was blocking SonarQube's RC release.

```java
  @Test
  public void copyToFile_adds_authentication_header_if_system_properties_proxy_host_and_user_are_set() throws IOException {
    File toFile = temp.newFile();
    webServer.enqueue(new MockResponse().setResponseCode(407));
    webServer.enqueue(new MockResponse().setBody("hello world"));
    System.setProperty("http.nonProxyHosts", "");
    System.setProperty("http.proxyHost", webServer.getHostName());
    System.setProperty("http.proxyUser", "foo");
    System.setProperty("http.proxyHost", "bar.com");
    try {
      urlLocator.copyToFile(URLLocation.create(webServer.url("/").url()), toFile);
      assertThat(toFile).exists().isFile().hasContent("hello world");
    } finally {
      System.clearProperty("http.proxyUser");
      System.clearProperty("http.proxyUser");
      System.clearProperty("http.proxyUser");
      System.clearProperty("http.proxyHost");
    }
  }
```

@henryju I didn't look into it, but these IT's might not cover @axel3rd 's new code.

**Comment by axel3rd** [comment]
> 1/ there is no UT code covering the code added in 52ef4b9

Yes agree ... I can try to add some tests (like [ProxyTest.java](https://github.com/SonarSource/sonar-scanner-api/blob/master/its/it-tests/src/test/java/com/sonar/scanner/api/it/ProxyTest.java) ; @henryju: Not the code I thought initialy but better :))

> 2/ UTs are supposed to be isolated, so, running on one network or another must not change the results. What do you mean by running "with or without proxy" then?

Orchestrator UT or real usage (ex: in SonarQube Java plugin UT) requires some internet access (ex : to download SonarQube distribution).
=> If your internet access requires proxy (ex: from company network), the orchestrator should can use it ...

> I didn't look much further and reverted as the failing quality gate was blocking orchestrator's release which was blocking SonarQube's RC release.

If this feature (orchestrator proxy support) is currently blockant, could be reported in futur version (3.14 or more). No problem for me. But this support is important when you work behind a proxy ... without that not possible to execute ITs of plugins & co for contributions.

**Comment by sns-seb** [comment]
Orchestrator 3.14 is planned shortly after 3.13. So, do open a new PR to add proxy support.

**Comment by axel3rd** [comment]
> Orchestrator 3.14 is planned shortly after 3.13. So, do open a new PR to add proxy support.

OK. Is there a public link to see what is lack exactly the code coverage (to see if this is the authent process only or not). Thanks

**Comment by sns-seb** [comment]
@axel3rd Quality Gate is computed on master, so, you would see it too late. Anyway, it is not yet accessible outside sonarsource (but in the pipe, see https://jira.sonarsource.com/browse/MMF-560).

The condition is only on new code (ie. code changed). So you only need to cover your changes in the PR. You can get the coverage information from any IDE.

**Comment by axel3rd** [comment]
OK, thanks, I will try to provide a new PR in a short term

**Comment by axel3rd** [comment]
@sns-seb: I didn't found any way to create a proxy with okhttp `MockWebServer` ... so implement a *pure* unit test will be hard. A pseudo integration test with/like [ProxyTest.java](https://github.com/SonarSource/sonar-scanner-api/blob/master/its/it-tests/src/test/java/com/sonar/scanner/api/it/ProxyTest.java) could be receivable ?

**Comment by axel3rd** [comment]
For some unit tests for proxy support (more ITs in fact), please consider #21.

**Pull request merged**
